
version: '2'

volumes:
    peerbb3.retailer.com:

networks:
    test:

services:
    peerbb3.retailer.com:
        image: hyperledger/fabric-peer:2.2
        dns_search: .
        container_name: peerbb3.retailer.com
        environment:
            - GODEBUG=netdns=go
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=false
            - CORE_PEER_GOSSIP_ORGLEADER=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peerbb3.retailer.com
            - CORE_PEER_ADDRESS=peerbb3.retailer.com:11091
            - CORE_PEER_LISTENADDRESS=0.0.0.0:11091
            - CORE_PEER_CHAINCODEADDRESS=peerbb3.retailer.com:11092
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11092
            - CORE_PEER_GOSSIP_BOOTSTRAP=peerbb2.retailer.com:11081
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerbb3.retailer.com:11091
            - CORE_PEER_LOCALMSPID=bigbazarMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peerbb3.retailer.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
            - CORE_METRICS_PROVIDER=prometheus
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb3.retailer.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb3.retailer.com/tls:/etc/hyperledger/fabric/tls
            - peerbb3.retailer.com:/var/hyperledger/retailer
        ports:
            - 11091:11091
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start --peer-chaincodedev=true  
        networks:
            - test
        
    cli_peerbb3.retailer.com:
        container_name: cli_peerbb3.retailer.com
        image: hyperledger/fabric-tools:2.2
        tty: true
        stdin_open: true
        environment:
            - SYS_CHANNEL=orderer-channel
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=peerbb3.retailer.com
            - CORE_PEER_ADDRESS=peerbb3.retailer.com:11091
            - CORE_PEER_LOCALMSPID=bigbazarMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/retailer.com/peers/peerbb3.retailer.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/retailer.com/peers/peerbb3.retailer.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/retailer.com/peers/peerbb3.retailer.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/retailer.com/users/Admin@retailer.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - peerbb3.retailer.com
        networks:
            - test
        
    couchdb_peerbb3.retailer.com:
        container_name: couchdb_peerbb3.retailer.com
        image: couchdb:3.1.1
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - 2010:5984
        networks:
            - test
