OrdererOrgs:
  - Name: orderer
    Domain: service.com
    EnableNodeOUs: false
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: RapidInnovation
    Domain: ri.blockchain.io
    EnableNodeOUs: false
    Specs:
      - Hostname: ripeer1
      - Hostname: ripeer2
    Users: 
      Count: 1

  - Name: Honda
    Domain: honda.bigwing.com
    EnableNodeOUs: false
    Specs:
      - Hostname: hondapeer1
      - Hostname: hondapeer2
    Users:
      Count: 1