Organizations:
    - &fssai
        Name: fssaiMSP
        ID: fssaiMSP
        MSPDir: ../crypto-config/peerOrganizations/safety.io/peers/peerfssai1.safety.io/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('fssaiMSP.peer', 'fssaiMSP.admin', 'fssaiMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('fssaiMSP.peer', 'fssaiMSP.admin', 'fssaiMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('fssaiMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('fssaiMSP.peer')"
        AnchorPeers:
            Host: peerfssai1.safety.io
            Port: 12050
