Profiles:
  newProfile:
    Consortium: SampleConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    Capabilities:
      V2_0: true
    Application:
      ACLs:
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetChannelConfig: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Writers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers
      Organizations:
        - Name: bigbazar
          ID: bigbazarMSP
          MSPDir: /home/ubuntu/fabric/hyperledger/coffee_poc/updateChannel/../crypto-config/peerOrganizations/retailer.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: "OR('bigbazarMSP.member', 'bigbazarMSP.peer', 'bigbazarMSP.admin', 'bigbazarMSP.client')"
            Writers:
              Type: Signature
              Rule: "OR('bigbazarMSP.member', 'bigbazarMSP.peer', 'bigbazarMSP.admin', 'bigbazarMSP.client')"
            Admins:
              Type: Signature
              Rule: "OR('bigbazarMSP.admin')"
            Endorsement:
              Type: Signature
              Rule: "OR('bigbazarMSP.peer', 'bigbazarMSP.admin')"
          AnchorPeers:
            Host: peerbb1.retailer.com
            Port: 11051
        - Name: teafarm
          ID: teafarmMSP
          MSPDir: /home/ubuntu/fabric/hyperledger/coffee_poc/updateChannel/../crypto-config/peerOrganizations/production.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: "OR('teafarmMSP.member', 'teafarmMSP.peer', 'teafarmMSP.admin', 'teafarmMSP.client')"
            Writers:
              Type: Signature
              Rule: "OR('teafarmMSP.member', 'teafarmMSP.peer', 'teafarmMSP.admin', 'teafarmMSP.client')"
            Admins:
              Type: Signature
              Rule: "OR('teafarmMSP.admin')"
            Endorsement:
              Type: Signature
              Rule: "OR('teafarmMSP.peer', 'teafarmMSP.admin')"
          AnchorPeers:
            Host: peertf1.production.com
            Port: 8051
      Policies:
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        V2_0: true
