Profiles:
  newProfile:
    Consortium: SampleConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    Capabilities:
      V2_0: true
    Application:
      ACLs:
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetChannelConfig: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Writers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers
      Organizations:
        - Name: bigbazar
          ID: bigbazarMSP
          MSPDir: /home/ubuntu/hyperledger/coffee_poc/crypto-config/peerOrganizations/retailer.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: "OR('bigbazarMSP.member', 'bigbazarMSP.peer', 'bigbazarMSP.admin', 'bigbazarMSP.client')"
            Writers:
              Type: Signature
              Rule: "OR('bigbazarMSP.member', 'bigbazarMSP.peer', 'bigbazarMSP.admin', 'bigbazarMSP.client')"
            Admins:
              Type: Signature
              Rule: "OR('bigbazarMSP.admin')"
            Endorsement:
              Type: Signature
              Rule: "OR('bigbazarMSP.peer', 'bigbazarMSP.admin')"
          AnchorPeers:
            Host: peerbb1.retailer.com
            Port: 11051
        - Name: tata
          ID: tataMSP
          MSPDir: /home/ubuntu/hyperledger/coffee_poc/crypto-config/peerOrganizations/manufacturer.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: "OR('tataMSP.member', 'tataMSP.peer', 'tataMSP.admin', 'tataMSP.client')"
            Writers:
              Type: Signature
              Rule: "OR('tataMSP.member', 'tataMSP.peer', 'tataMSP.admin', 'tataMSP.client')"
            Admins:
              Type: Signature
              Rule: "OR('tataMSP.admin')"
            Endorsement:
              Type: Signature
              Rule: "OR('tataMSP.peer', 'tataMSP.admin')"
          AnchorPeers:
            Host: peertm1.manufacturer.com
            Port: 9051
      Policies:
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        V2_0: true
