
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers

        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers

        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers

        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers

        lscc/ChaincodeExists: /Channel/Application/Readers

        lscc/GetDeploymentSpec: /Channel/Application/Readers

        lscc/GetChaincodeData: /Channel/Application/Readers

        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

        qscc/GetChainInfo: /Channel/Application/Readers

        qscc/GetBlockByNumber: /Channel/Application/Readers

        qscc/GetBlockByHash: /Channel/Application/Readers

        qscc/GetTransactionByID: /Channel/Application/Readers

        qscc/GetBlockByTxID: /Channel/Application/Readers

        cscc/GetConfigBlock: /Channel/Application/Readers

        cscc/GetChannelConfig: /Channel/Application/Readers

        peer/Propose: /Channel/Application/Writers

        peer/ChaincodeToChaincode: /Channel/Application/Writers

        event/Block: /Channel/Application/Readers

        event/FilteredBlock: /Channel/Application/Readers

    Organizations:

    Policies: &ApplicationDefaultPolicies
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

