Error: Error updating document at index 0: yaml: unknown anchor 'ChannelCapabilities' referenced
Usage:
  yq merge [initial_yaml_file] [additional_yaml_file]... [flags]

Aliases:
  merge, m

Examples:

yq merge things.yaml other.yaml
yq merge --inplace things.yaml other.yaml
yq m -i things.yaml other.yaml
yq m --overwrite things.yaml other.yaml
yq m -i -x things.yaml other.yaml
yq m -i -a things.yaml other.yaml
      

Flags:
  -e, --allow-empty   allow empty yaml files
  -a, --append        update the yaml file by appending array values
  -d, --doc string    process document index number (0 based, * for all documents) (default "0")
  -h, --help          help for merge
  -i, --inplace       update the yaml file inplace
  -x, --overwrite     update the yaml file by overwriting existing values

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode

