version: '2'

volumes:
  honda-peer-1:
  honda-peer-2:
  ri-peer-1:
  ri-peer-2:
  orderer.service.com:

services:

  honda-peer-1:
    container_name: hondapeer1.honda.bigwing.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=hondapeer1.honda.bigwing.com
      - CORE_PEER_ADDRESS=hondapeer1.honda.bigwing.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=hondapeer1.honda.bigwing.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=hondapeer1.honda.bigwing.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hondapeer1.honda.bigwing.com:7051
      - CORE_PEER_LOCALMSPID=HondaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/honda.bigwing.com/peers/hondapeer1.honda.bigwing.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/honda.bigwing.com/peers/hondapeer1.honda.bigwing.com/tls:/etc/hyperledger/fabric/tls
        - honda-peer-1:/var/hyperledger/production
    ports:
      - 7051:7051

  honda-peer-2:
    container_name: hondapeer2.honda.bigwing.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=hondapeer2.honda.bigwing.com
      - CORE_PEER_ADDRESS=hondapeer2.honda.bigwing.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=hondapeer2.honda.bigwing.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=hondapeer2.honda.bigwing.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hondapeer2.honda.bigwing.com:8051
      - CORE_PEER_LOCALMSPID=HondaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/honda.bigwing.com/peers/hondapeer2.honda.bigwing.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/honda.bigwing.com/peers/hondapeer2.honda.bigwing.com/tls:/etc/hyperledger/fabric/tls
        - honda-peer-2:/var/hyperledger/production
    ports:
      - 8051:8051

  ri-peer-1:
    container_name: ripeer1.ri.blockchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=ripeer1.ri.blockchain.io
      - CORE_PEER_ADDRESS=ripeer1.ri.blockchain.io:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=ripeer1.ri.blockchain.io:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=ripeer1.ri.blockchain.io:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ripeer1.ri.blockchain.io:9051
      - CORE_PEER_LOCALMSPID=RapidInnovationMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ri.blockchain.io/peers/ripeer1.ri.blockchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ri.blockchain.io/peers/ripeer1.ri.blockchain.io/tls:/etc/hyperledger/fabric/tls
        - ri-peer-1:/var/hyperledger/production
    ports:
      - 9051:9051
    
  ri-peer-2:
    container_name: ripeer2.ri.blockchain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=ripeer2.ri.blockchain.io
      - CORE_PEER_ADDRESS=ripeer2.ri.blockchain.io:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=ripeer2.ri.blockchain.io:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=ripeer2.ri.blockchain.io:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ripeer2.ri.blockchain.io:10051
      - CORE_PEER_LOCALMSPID=RapidInnovationMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ri.blockchain.io/peers/ripeer2.ri.blockchain.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ri.blockchain.io/peers/ripeer2.ri.blockchain.io/tls:/etc/hyperledger/fabric/tls
        - ri-peer-2:/var/hyperledger/production
    ports:
      - 10051:10051

  orderer.service.com:
    container_name: orderer.service.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artefacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/service.com/orderers/orderer.service.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/service.com/orderers/orderer.service.com/tls/:/var/hyperledger/orderer/tls
        - orderer.service.com:/var/hyperledger/production/orderer
    ports:
      - 6050:6050    