# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer:
  hondapeer1:
  hondapeer2:
  ripeer1:
  ripeer2:
  # peer0.org2.example.com:

networks:
  test:
    name: test

services:

  orderer:
    extends:
      file: docker-compose-base.yaml
      service: orderer
    container_name: orderer
    networks:
      - test

  hondapeer1:
    extends:
      file:   docker-compose-base.yaml
      service: hondapeer1
    container_name: hondapeer1
    networks:
      - test

  hondapeer2:
    extends:
      file:   docker-compose-base.yaml
      service: hondapeer2
    container_name: hondapeer2
    networks:
      - test

  ripeer1:
    extends:
      file:   docker-compose-base.yaml
      service: ripeer1
    container_name: ripeer1
    networks:
      - test

  ripeer2:
    extends:
      file:   docker-compose-base.yaml
      service: ripeer2
    container_name: ripeer2
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=orderer-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=hondapeer1.honda.bigwing.com:7051
      - CORE_PEER_LOCALMSPID=HondaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/honda.bigwing.com/peers/hondapeer1.honda.bigwing.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/honda.bigwing.com/peers/hondapeer1.honda.bigwing.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/honda.bigwing.com/peers/hondapeer1.honda.bigwing.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/honda.bigwing.com/users/Admin@honda.bigwing.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artefacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer
      - hondapeer1
      - hondapeer2
      - ripeer1
      - ripeer2
    networks:
      - test
 
  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=hondapeer1.honda.bigwing.com:7051
      - CORE_PEER_LOCALMSPID=HondaMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincode
    command: /bin/sh -c 'sleep 6000000'
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        - ./../chaincode:/opt/gopath/src/chaincode
    depends_on:
      - orderer
      - ripeer1
      - ripeer2
      - hondapeer1
      - hondapeer2