version: '2'

volumes:
  ca.safety.io:

services:
  ca.safety.io:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.safety.io
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2056
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee_test
    ports:
      - "2056:2056"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../fabric-ca/fssai:/etc/hyperledger/fabric-ca-server
      - ../../persistence-data/ca.safety.io:/etc/hyperledger
    container_name: ca.safety.io
    hostname: ca.safety.io
    networks:
      - test