Organizations:
    - &OrdererOrgs
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../crypto-config/ordererOrganizations/service.com/msp
        Policies: 
            Readers:
                Type: Signature
                Rule: "OR(OrdererMSP.member)"
            Writer:
                Type: Signature
                Rule: "OR(OrdererMSP.member)"
            Admins: 
                Type: Signature
                Rule: "OR(OrdererMSP.member)"
        OrdererEndpoints:
            - orderer.service.com:7050 # hostname.domain:<port>
    
    - &Honda
        Name: Honda
        ID: HondaMSP
        MSPDir: ../crypto-config/peerOrganizations/honda.bigwing.com/msp
        Policies: 
            Readers:
                Type: Signature
                Rule: "OR(HondaMSP.member,HondaMSP.client)"
            Writer:
                Type: Signature
                Rule: "OR(HondaMSP.member, HondaMSP.admin, HondaMSP.peer)"
            Admins: 
                Type: Signature
                Rule: "OR(HondaMSP.member)" 
        AnchorPeers: #for inter-channel communication 
            Host: honda-peer1.honda.bigwing.com
            Port: 1061

    - &RapidInnovation
        Name: RapidInnovation
        ID: RapidInnovationMSP
        MSPDir: ../crypto-config/peerOrganizations/ri.blockchain.io/msp
        Policies: 
            Readers:
                Type: Signature
                Rule: "OR(RapidInnovationMSP.member)"
            Writer:
                Type: Signature
                Rule: "OR(RapidInnovationMSP.member, RapidInnovationMSP.peer, RapidInnovationMSP.admin)"
            Admins: 
                Type: Signature
                Rule: "OR(RapidInnovationMSP.member)" 
        AnchorPeers: #for inter-channel communication 
            Host: ripeer1.ri.blockchain.io
            Port: 1051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies: 
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admin:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities: 
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: Solo
    Addresses: 
        - orderer.service.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    GenesisProfile:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Honda
                    - *RapidInnovation
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Honda
                - *RapidInnovation
            Capabilities:
                <<: *ApplicationCapabilities